from hermes.core.runtime import HermesRuntime
import json

def run_analysis_task():
    runtime = HermesRuntime()
    
    task = "Analyze the current 5-layer memory status and provide skill solidification suggestions."
    print(f"\n[Action] Running analysis task: '{task}'")
    
    runtime.execute_task(task)
    
    # 產出分析報告
    report_path = "C:/Users/樺電腦/Desktop/HERMES_MEMORY_ANALYSIS.md"
    summary = runtime.get_status()
    
    report_content = f"""# Hermes Agent OS: 記憶體系分析報告

## 1. 執行概況
- **任務**: {task}
- **結果**: {summary['current_state']}
- **Token 消耗**: {summary['metrics']['metrics']['token_usage']['total']}

## 2. 記憶層現狀
- **Working Memory**: 活躍
- **Semantic Memory**: 已儲存 {len(runtime.memory.semantic.data)} 筆會話紀錄
- **User Modeling**: 已載入用戶偏好
- **Procedural Memory**: 待固化新技能

## 3. 經驗固化建議 (Skill Solidification)
根據執行軌跡，建議將以下流程固化為技能：
- `project_arch_checker`: 自動化掃描目錄結構與設定檔。
- `safety_audit_loop`: 強化執行前的計畫驗證流程。

---
*Generated by Hermes Agent OS*
"""
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write(report_content)
    print(f"\n[Info] Analysis report exported to: {report_path}")

if __name__ == "__main__":
    run_analysis_task()
